config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  ## postsという一覧画面（index）、詳細画面（show）、
  #  登録画面（new）、登録処理（create）、編集画面（edit）、
  #  更新処理（update）、削除処理（destroy）へのURLを自動発行
  resources :posts do
    # postレコードに関連づけられたComment機能のルーティング
    resources :comments
  end

  #ルート（/）にアクセスしたらpostsコントローラーのindexメソッド実行する
  root :to => 'posts#index'
  
  
  
  
  get 'events/index'
  get 'events/new'
  
  get 'events/:year/:month/:date/edit' => 'events#edit'
  
 

  post 'events' => 'events#create'
  
  get 'events/:num' => 'events#index'
  get 'events/:year/:month/:date' => 'events#show' 
  patch 'events/:year/:month/:date/edit' => 'events#update' 
  put 'events/:year/:month/:date/edit' => 'events#update'

  delete 'events/:year/:month/:date' => 'events#destroy'
  
  
  
  

  


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  
  # commenterは入力が必須（presence -> 存在していることが必須）
  validates :commenter, :presence => true

  # bodyは入力が必須かつ、文字数の長さが最低５は必須
  validates :body, :presence => true,
                      :length => { :minimum => 5 }
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  
  # titleは入力が必須（presence -> 存在していることが必須）
  validates :title, :presence => true

  # titleは入力が必須かつ、文字数の長さが最低５は必須
  validates :content, :presence => true,
                      :length => { :minimum => 5 }

  # PostオブジェクトはたくさんのCommentオブジェクトを持つ
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def destroy
        # idで指定したオブジェクトを取得
        @comment = Comment.find(params[:id])
        # オブジェクトの削除
        @comment.destroy
        # json形式で@commentの内容をcommentとしてViewに渡す
        @post = Post.find(params[:post_id])
        redirect_to post_path(@post)       
end

    def create
        # idで指定したPostオブジェクトをデータベースから取得  
        @post = Post.find(params[:post_id])

        # フォームに入力されたデータをidで指定したPostオブジェクトに
        # 関連するコメントオブジェクトを作成し、データベースに登録
        # .create == (.new + .save)
        @comment = Post.find(params[:post_id]).comments.create(comments_params)

        if @comment.save
            # 指定したポスト表示ページにリダイレクト
            redirect_to post_path(@post)
        # もしデータベースへの保存が成功しなかったら
        else
            # メソッド処理後にクライアントに返すhtmlのテンプレートをshowに指定
            render :template => "posts/show"

        end
    end

    private
        def comments_params
            params.require(:comment).permit(:commenter, :body)
        end
   
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        if params[:num].nil? then
            @day = Date.today
        elsif params[:num] == '-6' then
            @day = Date.today.months_ago(6)
        elsif params[:num] == '-5' then
            @day = Date.today.months_ago(5)
        elsif params[:num] == '-4' then
            @day = Date.today.months_ago(4)
        elsif params[:num] == '-3' then
            @day = Date.today.months_ago(3)
        elsif params[:num] == '-2' then
            @day = Date.today.months_ago(2)
        elsif params[:num] == '-1' then
            @day = Date.today.last_month
        elsif params[:num] == '0' then
            @day = Date.today
        elsif params[:num] == '1' then
            @day = Date.today.next_month
        elsif params[:num] == '2' then
            @day = Date.today.months_since(2)
        elsif params[:num] == '3' then
            @day = Date.today.months_since(3)
        elsif params[:num] == '4' then
            @day = Date.today.months_since(4)
        elsif params[:num] == '5' then
            @day = Date.today.months_since(5)
        else
            @day = Date.today
        end
        @events = Event.where("group_id = ?")
    end
    
    #def index
        # Postから全てのデータを引っ張りだし、インスタンス変数postsに代入
    #    @year = params[:year]
    #    @month = params[:month]
    #    @day = params[:day]
    #    @events = Event.where("group_id = ?")
    #end
    


    def show
        @event = Event.find_by(year: params[:year],month: params[:month], date: params[:date])
  
    end

    def new
        # 空のPostモデルオブジェクトを生成し、インスタンス変数postsに代入
        @event = Event.new
    end

    def edit
        @event = Event.find_by(year: params[:year], month: params[:month], date: params[:date])
    end

    

    def update
        # Viewから渡されたデータを元にオブジェクトを生成
        @event = Event.find_by(year: params[:year], month: params[:month], date: params[:date])
        if @event.update(event_params)
            # もしDBへの生成したオブジェクトの保存が成功したら/postsへリダイレクト（移動）    
            redirect_to events_index_path
            flash[:notice] = '更新されました！'
        else
            # もしDBへの生成したオブジェクトの保存が成功しなかったら/posts/newへ戻ってnewビューを直させる 
            render action: 'edit'
        end
    end

    def destroy
        # idで指定したオブジェクトを取得
        @event = Event.find_by(year: params[:year],month: params[:month], date: params[:date])
        # オブジェクトの削除
        @event.destroy
        # posts（index）にリダイレクト
        redirect_to events_index_path
        
        
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            # もしDBへの生成したオブジェクトの保存が成功したら/postsへリダイレクト（移動）  
            redirect_to events_index_path
            flash[:notice] = "作成されました！"
        else
            # もしDBへの生成したオブジェクトの保存が成功しなかったら/posts/newへ戻ってnewビューを直させる 
            render action: 'new'
        end
    end
    private
        def event_params
            # submitしたデータのうち、Model作成に必要なものを
            # permitの引数に指定する
            params.require(:event).permit(:year, :month, :date, :title, :content)
        end
end

app/controllers/posts_controller.rb
# coding: utf-8

class PostsController < ApplicationController

    def index
        # Postから全てのデータを引っ張りだし、インスタンス変数postsに代入
        @posts = Post.all
        @events = Event.all
    end



    def show
        # PostモデルのfindメソッドにparamsでURLから受け取ったIDを引数として与え、
        # そのデータが見つかったらインスタンス変数postに代入
        @post = Post.find(params[:id])
        # Postオブジェクトのidと紐付けられているcomments
        @comment = Post.find(params[:id]).comments.build
    end

    def new
        # 空のPostモデルオブジェクトを生成し、インスタンス変数postsに代入
        @post = Post.new
    end

    def edit
        # 指定したオブジェクトの取得
        @post = Post.find(params[:id])
    end

    

    def update
        # Viewから渡されたデータを元にオブジェクトを生成
        @post = Post.find(params[:id])
        if @post.update(post_params)
            # もしDBへの生成したオブジェクトの保存が成功したら/postsへリダイレクト（移動）    
            redirect_to posts_path
            flash[:notice] = '更新されました！'
        else
            # もしDBへの生成したオブジェクトの保存が成功しなかったら/posts/newへ戻ってnewビューを直させる 
            render action: 'edit'
        end
    end

    def destroy
        # idで指定したオブジェクトを取得
        @post = Post.find(params[:id])
        # オブジェクトの削除
        @post.destroy
        # posts（index）にリダイレクト
        redirect_to posts_path
        
        
    end

    def create
        @post = Post.new(post_params)
        if @post.save
            # もしDBへの生成したオブジェクトの保存が成功したら/postsへリダイレクト（移動）  
            redirect_to posts_path
            flash[:notice] = "作成されました！"
        else
            # もしDBへの生成したオブジェクトの保存が成功しなかったら/posts/newへ戻ってnewビューを直させる 
            render action: 'new'
        end
    end
    private
        def post_params
            # submitしたデータのうち、Model作成に必要なものを
            # permitの引数に指定する
            params.require(:post).permit(:title, :content)
        end

    

    



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    日付
    <%= f.select :year, [["2018","2018"],["2019","2019"],["2020","2020"]], :selected => "#{flash[:y]}" %>
    <%= f.select :month, [["1","01"],["2","02"],["3","03"],["4","04"],["5","05"],["6","06"],["7","07"],["8","08"],["9","09"],["10","10"],["11","11"],["12","12"]], :selected => "#{flash[:m]}" %>
    <%= f.select :date, [["1","01"],["2","02"],["3","03"],["4","04"],["5","05"],["6","06"],["7","07"],["8","08"],["9","09"],["10","10"],["11","11"],["12","12"],["13","13"],["14","14"],["15","15"],["16","16"],["17","17"],["18","18"],["19","19"],["20","20"],["21","21"],["22","22"],["23","23"],["24","24"],["25","25"],["26","26"],["27","27"],["28","28"],["29","29"],["30","30"],["31","31"]], :selected => "#{flash[:d]}" %><br />
    <br>
    <!--もし@postにエラーがあったら-->
    <% if @event.errors.any? %>
    <!--順序無しリスト-->
    <ul>
        <!--エラーの数だけループ-->
        <% @event.errors.full_messages.each do |msg| %>
        <!--メッセージの内容を表示   -->
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
    <% end %>

    <!--titleに対するテキストフィールド-->
    <div class="field">
        <!--titleに対するテキストフィールド-->
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br>
    <!--contentに対するテキストエリア（５行分）-->
    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, :rows => 5 %>
    </div>
    <br>
    <!--送信ボタン（createメソッドへ）-->
    <div class="actions">
        <%= f.submit %>
    </div>
<br>
<% end %>

app/views/events/edit.html.erb
<div class="contents">
    <div class="titleposi">
        <h1>New event</h1>
    </div>
    <br>
    <br>
    <%= form_for(@event, url: {action: :update }) do |f| %>
    
    
    <!--もし@postにエラーがあったら-->
    <% if @event.errors.any? %>
    <!--順序無しリスト-->
    <ul>
        <!--エラーの数だけループ-->
        <% @event.errors.full_messages.each do |msg| %>
        <!--メッセージの内容を表示   -->
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
    <% end %>

    <!--titleに対するテキストフィールド-->
    <div class="field">
        <!--titleに対するテキストフィールド-->
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br>
    <!--contentに対するテキストエリア（５行分）-->
    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, :rows => 5 %>
    </div>
    <br>
    <!--送信ボタン（createメソッドへ）-->
    <div class="actions">
        <%= f.submit %>
    </div>
<br>
<% end %>
<% e = @event %>
<%= link_to 'Delete', "/events/#{e.year}/#{e.month}/#{e.date}",  method: :delete , data: { confirm: 'Sure?' }  %>
</div>

app/views/events/index.html.erb
<div class = "calendarbody">
    <% today = @day %>

  <table align="center" frame="border" rules="all">
    <caption>
    <ul class = "menu">
      <li><%= link_to "#{Date.today.months_ago(6).strftime('%-m')}月","-6",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_ago(5).strftime('%-m')}月","-5",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_ago(4).strftime('%-m')}月","-4",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_ago(3).strftime('%-m')}月","-3",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_ago(2).strftime('%-m')}月","-2",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.last_month.strftime('%-m')}月","-1",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.strftime('%-m')}月","0",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.next_month.strftime('%-m')}月","1",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_since(2).strftime('%-m')}月","2",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_since(3).strftime('%-m')}月","3",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_since(4).strftime('%-m')}月","4",class: "linkline"%></li>
      <li><%= link_to "#{Date.today.months_since(5).strftime('%-m')}月","5",class: "linkline"%></li>
    </ul>
    <h1>
        <%= today.strftime("%Y年%-m月") %>
    </h1>
    </caption>
    <tr>
      <th width="80" height="50" bgcolor="#ffe8ff"><font color="red">日</font></th>
      <th width="80" height="50">月</th>
      <th width="80" height="50">火</th>
      <th width="80" height="50">水</th>
      <th width="80" height="50">木</th>
      <th width="80" height="50">金</th>
      <th width="80" height="50" bgcolor="#afeeee"><font color="blue">土</font></th>
    </tr>
    <% month = today.strftime('%m')%>
    <% d = today.at_beginning_of_month.at_beginning_of_week(:sunday)%>
    <% 1.upto(6).each do|i|%>
    <tr>
        <% (d..d.end_of_week(:sunday)).each do|c|%>
          <th width="80" height="50" align="left" valign="top">
            <% y = c.strftime('%Y')%>
            <% m = c.strftime('%m')%>
            <% p = c.strftime('%d')%>
            <% e = Event.find_by(year: y, month: m, date: p) %>
            <% if e != nil then %>
              <div class = "posi"><%="#{c.strftime('%-d')}"%></div>
              <h3>
              <%= link_to "#{e.title}", "#{y}/#{m}/#{p}",class:"linkline"%>
              </h3>
            <% else %>
               <div class = "posi"><%="#{c.strftime('%-d')}"%></div>
            <% end %>
          </th>
          
        <% end %>
    </tr>
  <% d = d + 1.week %>
  <% end %>
</table>
<br />
<%= link_to "add event!", events_new_path ,class: "linkline"%>
    

    
</div>

app/views/events/new.html.erb
<div class = "contents">
<div class="titleposi">
    <h1>New event</h1>
</div>
<br>
<br>
<%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="contents">
<div class="titleposi">
    <h1>
        <%= @event.title %>
    </h1>
</div>
<p>
    <%= @event.content %>
</p>
<% e = @event %>

<%= link_to '戻る', events_index_path %><br /> 
<%= link_to 'Edit', "/events/#{e.year}/#{e.month}/#{e.date}/edit" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body style="background-color:#fff">
    
    <!-- header -->
    <%= render "posts/header"%>
    <!-- body -->
    <div class = "outline">
      <div class = "pagebody">
        
          <%= yield %>
    
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<!--@postに対するフォーム-->
<%= form_for(@post) do |f| %>

    <!--もし@postにエラーがあったら-->
    <% if @post.errors.any? %>
    <!--順序無しリスト-->
    <ul>
        <!--エラーの数だけループ-->
        <% @post.errors.full_messages.each do |msg| %>
        <!--メッセージの内容を表示   -->
        <li>
            <%= msg %>
        </li>
        <% end %>
    </ul>
    <% end %>

    <!--titleに対するテキストフィールド-->
    <div class="field">
        <!--titleに対するテキストフィールド-->
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <br />
    <!--contentに対するテキストエリア（５行分）-->
    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, :rows => 5 %>
    </div>
    <br />
    <!--送信ボタン（createメソッドへ）-->
    <div class="actions">
        <%= f.submit %>
    </div>
<br>
<% end %>

app/views/posts/_header.html.erb
<div class="header-fixed">
    <div class="header-bk">
        <div class="header_body">
            <div class="logo_posi">
                <div class="titlelogo">
                    <!--<%= link_to image_tag('logo.png', class: 'logo'), posts_path %>-->
                </div>
            </div>
            <div class = "menu _posi">
                <ul class = "h_menu">
                    <li><%= link_to "Home",posts_path%></li>
                    <li><%= link_to "Calendar", events_index_path %></li>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class = "contents">
<div class = "titleposi">
    <h1>Edit</h1>
</div>
<br>
<br>

<%= render 'form' %>


<%= link_to 'Delete', @post,  method: :delete , data: { confirm: 'Sure?' }  %>
<br>
</div>

app/views/posts/index.html.erb
<div class = "contents">
<%# 一時通知メッセージ %>
<div id="notice">
    <%= notice %>
</div>


<%# ヘッダー %>
<div class = "titleposi">
    <h1>Memo</h1>
</div>

    <%# 順序無しリスト %>
    <ul>
        <%# ループ %>
        <% @posts.each do |post| %>
                <li>
                    <%# 記事のタイトルにリンクを張ってリスト表示 %>
                    <%= link_to post.title, post_path(post),class: "linkline" %>
                    
                </li>
        <%# ループ終了 %>
        <% end %>
    </ul>
    
    <%# Newリンク %>
<%= link_to 'add!', new_post_path , class: "linkline" %>
</div>
<br />
<br />
<div class="contents">
    <div class="titleposi">
        <h1>Schedule</h1>
    </div>
    <ul>
        <%# ループ %>
        <% @events.each do |event| %>
                <li>
                    <%# 記事のタイトルにリンクを張ってリスト表示 %>
                    <p>
                        <%= "#{event.year}年#{event.month}月#{event.date}" %>
                    </p>
                    <%= link_to event.title, "events/#{event.year}/#{event.month}/#{event.date}",class: "linkline" %>
                    
                </li>
        <%# ループ終了 %>
        <% end %>
    </ul>
<%= link_to 'add!', events_new_path , class: "linkline" %>
<script>
    $(function () {
        //一定時間後に処理を行う（0.8秒後）
        setTimeout(function () {
            //noticeをゆっくりとフェードアウト
            $('#notice').fadeOut("slow");
        }, 800);

        
    });
</script>
</div>

app/views/posts/new.html.erb

<div class = "contents">
<div class = "titleposi">
    <h1>New Memo</h1>
</div>
<br>
<br>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class = "contents">
<div class = "titleposi">
    <h1>
        <%= @post.title %>
    </h1>
</div>
    

<%# 記事の内容 %>
<p>
    <%= @post.content %>
</p>
<!--
<%# ヘッダー（コメント） %>
    <h2>Comments</h2>
<%# 順序無しリスト %>
<ul>
    <%# コメントがあったら %>
    <% if @post.comments.any? %>
        <%# コメント数ループ %>
        <% @post.comments.each do |comment| %>
            <%# リストの内容 %>
                <li id = "comment_<%= comment.id %>">
                    <%# コメント本文 (by コメンター) %>
                    <%= comment.body %> (by <%= comment.commenter %>)
                    <%# コメント削除リンク %>
                    <%= link_to "Delete", [comment.post, comment],
                        # 実行するHTTPメソッド
                        method: :delete,
                        # 確認メッセージ 
                        data: { confirm: 'Sure?' }
                        # Ajaxを有効化（非同期処理）
                        
                        %>
                        
                </li>
        <% end %>
    <%# コメントが無かったら %>
    <% else %>
        <%# no comment yet. %>
        <li>no comment yet.</li>
    <% end %>
</ul>

<h2>Add a comment</h2>

<%# @postに対するコメントフォーム %>
<%= form_for([@post, @comment]) do |f| %>
    <%# もし@commentにエラーがあったら %>
    <% if @comment.errors.any? %>
        <%# 順序無しリスト %>
            <ul>
                <%# エラーの数だけループ %>
                <% @comment.errors.full_messages.each do |msg| %>
                <%# メッセージの内容を表示 %>
                <li>
                    <%= msg %>
                </li>
                <% end %>
            </ul>
    <% end %>

    <%# commenterに対するテキストフィールド %>
    <div class="field">
        <%# commenterに対するテキストフィールド %>
        <%= f.label :commenter %>
        <%= f.text_field :commenter %>
    </div>

    <%# bodyに対するテキストエリア（５行分） %>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, :rows => 5 %>
    </div>

    <%# 送信ボタン（createメソッドへ） %>
    <div class="actions">
        <%= f.submit %>
    </div>

<% end %>
-->
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to '戻る', posts_path %>

</div>